### ISSUE TITLE
Issue with number precision

### ISSUE THREAD

**Issue by mulderr** [leptonyu/odpic-raw#11]
It seems that `odpic-raw` looses precision when reading `NUMBER`s. Test query on [Chinook db](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Oracle.sql):

```sql
select avg(milliseconds) from track;
```

Results:
* 393599.2121039109334855837853268626891236 from SQLDeveloper
* 393599.2121039109188131988048553466796875 from Haskell as `Decimal`

Still looking into it but:
* it looks like the `FromDataField` instance for `Decimal` is missing a case for reading a full precision `NUMBER` from `DataNumBytes` which I would expect to happen here
* there may be some more issues with the `Storable Data` instance because `FromDataField Decimal` instance is always getting `DataDouble` while here I would expect `DataNumBytes`

Btw. any particular reasons to use `Decimal` over `Scientific`? They seem to be very similar but checking reverse dependencies `Scientific` is vastly more popular.

**Comment by leptonyu** [comment]
@mulderr thanks, I'll fix this. I have no particular reason to use `Decimal`, not familiar with decimal number in Haskell.

**Comment by leptonyu** [comment]
I use `cx_Oracle` to test get double value, it may be the problem of `ODPI-C`.

```python
# myscript.py

from __future__ import print_function

import cx_Oracle

# Connect as user "hr" with password "welcome" to the "oraclepdb" service running on this computer.
connection = cx_Oracle.connect("hr", "welcome", "localhost/orclpdb")

cursor = connection.cursor()
cursor.execute("""
    select avg(milliseconds) from track
    """)
for fname in cursor:
    print("Values:", fname)
```

logout 

```
Values: (393599.2121039109,)
```

**Comment by leptonyu** [comment]
@mulderr `ODPI-C` default use `NativeTypeDouble` when fetching `OracleTypeNumber` type numbers. I modified this behavior by `defineValue`, and it returns `393599.2121039109334855837853268626891236` as expected.

but I think it's better if `ODPI-C` could use `NativeTypeNumBytes` as default. Because `cx_Oracle` also has this behavior.


btw, I change `SQL` definition back to `String`, `bytestring` work not well with `UTF-8` characters, and it fails the tests.

**Comment by mulderr** [comment]
@leptonyu Ah, so the issue was deeper than I thought.

One as of yet still open question is whether it would be faster to use the defaults for `Double` and only have special handling for `Scientific`. A topic for another time.

Thanks for taking care of this!

**Comment by leptonyu** [comment]
@mulderr I will optimize later. Same problem with other `Numeric` types.
