### ISSUE TITLE
Missing Char type

### ISSUE THREAD

**Issue by mulderr** [leptonyu/odpic-raw#2]
Hello! 

I see Char is missing from [DataValue](https://github.com/leptonyu/odpic-raw/blob/master/src/Database/Dpi/Internal.chs#L328). The other [types](https://oracle.github.io/odpi/doc/user_guide/data_types.html) seem to be there, more or less.

I would somewhat expect odpic-raw to fairly closely follow upstream so I'm confused. Should Char be represented there?

**Comment by leptonyu** [comment]
@mulderr Thanks. I'll add `DataChar` in `DataValue`. Maybe later I should refactor `DataValue` to use Oracle raw types.

**Comment by leptonyu** [comment]
@mulderr I'm done. please check the change.

**Comment by mulderr** [comment]
Nice. Looks good. I'm hoping to find time to actually test it this weekend. Thanks!

**Comment by leptonyu** [comment]
Next PR, I'll use odpic raw data in `DataValue`, and provide a converter to convert to haskell data.
