### ISSUE TITLE
Definition of Data_Bytes

### ISSUE THREAD

**Issue by mulderr** [leptonyu/odpic-raw#5]
This looks very suspicious. Shouldn't we be using `ByteString` here?
```haskell
data Data_Bytes = Data_Bytes
  { bytes    :: L.Text
  , encoding :: Text
  } deriving Show
```
`Text` is by definition for Unicode strings.

I can prepare a PR if that's ok.

**Comment by leptonyu** [comment]
@mulderr Yeah, it's better to use `ByteString`. Please provide the PR

**Comment by mulderr** [comment]
Looking into it but it's turning out to be a larger refactor than I expected. There's a lot of places with the same issue.

My current understanding is that we should use `ByteString` everywhere and only provide `Text` interfaces where applicable on top of that. Low level stuff in particular should definitely not use `Text`. [postgresql-libpq](http://hackage.haskell.org/package/postgresql-libpq) as an example does not depend on `text` at all.

**Comment by leptonyu** [comment]
Okay, I'll fix this.
